name: Tarea PP2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar hora actual
        run: echo "La hora actual es $(TZ='America/Argentina/Buenos_Aires' date +'%Y-%m-%d %H:%M:%S')"

      - name: Elegir enlace aleatorio de YouTube
        id: generate_link
        run: |
          video_ids=("dQw4w9WgXcQ" "KpOtuoHL45Y" "r6O0xOqikzY")
          random_index=$(shuf -i 0-$(( ${#video_ids[@]} - 1 )) -n 1)
          random_video_id=${video_ids[$random_index]}
          echo "::set-output name=video_id::$random_video_id"

      - name: Muestra el enlace aleatorio de YouTube
        run: |
          video_id=${{ steps.generate_link.outputs.video_id }}
          echo "Enlace al video de YouTube: https://www.youtube.com/watch?v=$video_id"

      - name: Ver la ruta completa del directorio actual de trabajo  para un flujo de GitHub Actions
        run: pwd

      - name: Simplemente un mensaje por consola
        run: echo "Simplemente un mensaje por consola"